version: '3.5'

services:
  postgres-compose:
    image: postgres
    container_name: compose-postgres
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=banco
    ports:
      - "11232:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: compose-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "11233:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
